webapplikation/iotrace/accounts/routes.py
from flask import Blueprint, redirect, url_for, request, render_template, flash
from flask_login import current_user, login_user, logout_user, login_required
from iotrace import db, bcrypt
from iotrace.models import User, Device
from iotrace.accounts.forms import LoginForm, RegistrationForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from iotrace.accounts.utils import save_logo, save_picture, send_reset_email




accounts = Blueprint('accounts', __name__)


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('devices.curl_dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('devices.curl_dashboard'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('accounts/login.html', title='Login', form=form)

@accounts.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('devices.curl_dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You can now log in.', 'success')
        return redirect(url_for('accounts.login'))
    return render_template('accounts/register.html', title='Register', form=form)

@accounts.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@accounts.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        if form.logo.data:
            logo_file = save_logo(form.logo.data)
            current_user.logo_file = logo_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('accounts.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email        
    image_file = url_for('static', filename='images/profile_pics/' + current_user.image_file)
    logo_file = url_for('static', filename='images/account/' + current_user.logo_file)
    devices = Device.query.filter_by(user_id=current_user.id)
    return render_template('accounts/account.html', title='Account', image_file=image_file, logo_file=logo_file, devices=devices, form=form)

@accounts.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('devices.curl_dashboard'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email have been sent with instruction to reset your password', 'info')
        return redirect(url_for('accounts.login'))
    return render_template('accounts/reset_request.html', title='Reset Password', form=form)

@accounts.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('devices.curl_dashboard'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('accounts.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
       hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
       user.password = hashed_password
       db.session.commit()
       flash('Your password has now been updated! You can now log in.', 'success')
       return redirect(url_for('accounts.login'))
    return render_template('accounts/reset_token.html', title='Reset Password', form=form)

webapplikation/iotrace/devices/routes.py
import os
from flask import Blueprint, render_template, redirect, request, abort, flash, url_for
from flask_login import login_required, current_user
from iotrace import db
from iotrace.models import Device, DeviceData, TrackingDeviceTrigger, Xtel
from iotrace.devices.forms import CreateDeviceForm, EditDeviceForm
from iotrace.plots.plot import device_temp, device_humid, device_hpa, device_volt, device_lte_rssi, device_pos, all_device_pos, device_alarm1, device_alarm2
from iotrace.curls.curl import curl_all_device_pos, curl_device_temp, curl_device_humid, curl_device_hpa, curl_device_volt, curl_device_lte_rssi, curl_device_pos, curl_device_alarm1, curl_device_alarm2

devices = Blueprint('devices', __name__)

@devices.route('/dashboard')
@login_required
def curl_dashboard():
    devices = Device.query.filter_by(user_id=current_user.id).order_by(Device.devicetype.desc())
    device_data, all_device, GOOGLEMAPS_KEY = curl_all_device_pos(devices)
    logo_file = url_for('static', filename='images/profile_pics/' + current_user.logo_file)
    return render_template('devices/NEWdashboard.html',  title='Dashboard', devices=devices, GOOGLEMAPS_KEY=GOOGLEMAPS_KEY, logo_file=logo_file, all_device=all_device, device_data=device_data)

@devices.route('/dashboard/device/data/<device_id>')
@login_required
def curl_device(device_id):
    device = Device.query.get_or_404(device_id)
    if current_user != device.owner:
        abort(403)
    data = DeviceData.query.filter_by(device_mac=device.device_mac).order_by(DeviceData.timestamp.desc()).all()
    if device.devicetype != 'fire':
        temp = curl_device_temp(data)
        humid = curl_device_humid(data)
        hpa = curl_device_hpa(data)
        volt = curl_device_volt(data)
        lte_rssi = curl_device_lte_rssi(data)
        pos, label, icon, GOOGLEMAPS_KEY= curl_device_pos(device, data)
        return render_template('devices/NEWdevice.html', title=device.devicename, device=device, data=data, device_data=device.data_device, temp=temp, humid=humid, hpa=hpa, volt=volt, lte_rssi=lte_rssi, pos=pos, icon=icon, label=label, GOOGLEMAPS_KEY=GOOGLEMAPS_KEY)

    elif device.devicetype == 'fire':
        alarm_1 = curl_device_alarm1(data)
        alarm_2 = curl_device_alarm2(data)
        volt = curl_device_volt(data)
        lte_rssi = curl_device_lte_rssi(data)       
        return render_template('devices/NEWdevice.html', title=device.devicename, device=device, data=data, device_data=device.data_device, alarm_1=alarm_1, alarm_2=alarm_2, volt=volt, lte_rssi=lte_rssi)

@devices.route('/dashboard/device/new', methods=['GET', 'POST'])
@login_required
def add_device():
    form = CreateDeviceForm()
    if form.validate_on_submit():
        dev = Xtel.query.filter_by(device_mac=form.device_mac.data).first()
        device = Device(device_mac=form.device_mac.data ,devicename=form.devicename.data, devicetype=dev.devicetype, owner=current_user)
        db.session.add(device)
        db.session.commit()
        flash('The device have been added!', 'success')
        return redirect(url_for('devices.curl_dashboard'))
    return render_template('devices/add_device.html', title='Add Device', form=form)

@devices.route('/dashboard/device/edit/<device_id>', methods=['GET', 'POST'])
@login_required
def edit_device(device_id):
    device = Device.query.get_or_404(device_id)
    if device.owner != current_user:
        abort(403)
    value = TrackingDeviceTrigger.query.filter_by(device_id=device.id).first()
    form = EditDeviceForm()
    if value:       
        if form.validate_on_submit():
            device.devicename = form.devicename.data
            value.mintemp = form.mintemp.data
            value.maxtemp = form.maxtemp.data
            value.minhumid = form.minhumid.data
            value.maxhumid = form.maxhumid.data
            value.minhpa = form.minhpa.data
            value.maxhpa = form.maxhpa.data
            db.session.commit()
            flash('Your device has been updated', 'success')
            return redirect(url_for('devices.curl_device', device_id=device.id))
        elif request.method == 'GET':
            form.devicename.data = device.devicename
            form.mintemp.data = value.mintemp
            form.maxtemp.data = value.maxtemp
            form.minhumid.data = value.minhumid
            form.maxhumid.data = value.maxhumid
            form.minhpa.data = value.minhpa
            form.maxhpa.data = value.maxhpa
        return render_template('devices/edit_device.html', title='Update Device', form=form, device=device)
    else:    
        if form.validate_on_submit():
            device.devicename = form.devicename.data
            value = TrackingDeviceTrigger(device_id=device.id ,mintemp=form.mintemp.data, maxtemp=form.maxtemp.data, minhumid=form.minhumid.data, maxhumid=form.maxhumid.data, minhpa=form.minhpa.data, maxhpa=form.maxhpa.data)
            db.session.add(value)
            db.session.commit()
            flash('The values have been added', 'success')
            return redirect(url_for('devices.curl_device', device_id=device.id))
        elif request.method == 'GET':
            form.devicename.data = device.devicename
        return render_template('devices/edit_device.html', title='Update Device', form=form, device=device)



@devices.route('/dashboard/device/delete/<device_id>', methods=['POST'])
@login_required
def delete_device(device_id):
    device = Device.query.get_or_404(device_id)
    if device.owner != current_user:
        abort(403)
    db.session.delete(device)
    db.session.commit()
    flash('Your device has been deleted!', 'success')
    return redirect(url_for('devices.curl_dashboard'))

webapplikation/iotrace/main/routes.py
import os
import datetime
import json
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import login_required, current_user
from flask_admin.contrib.sqla import ModelView
from iotrace import db, admin
from iotrace.models import User, Device, DeviceData, TrackingDeviceTrigger, Xtel
from iotrace.main.forms import GenerateTrackingDeviceData

main = Blueprint('main', __name__)


class Admin_Model_View(ModelView):
    def is_accessible(self):
        if current_user.id == 1 or current_user.role == 'admin':
            return True
        else:
            return False
admin.add_view(Admin_Model_View(User, db.session))
admin.add_view(Admin_Model_View(Device, db.session))
admin.add_view(Admin_Model_View(DeviceData, db.session))
admin.add_view(Admin_Model_View(TrackingDeviceTrigger, db.session))
admin.add_view(Admin_Model_View(Xtel, db.session))

#Dette er vores startside og viser index.html 
@main.route('/')
@main.route(('/home'))
def home(methods=['GET', 'POST']):    
    if current_user.is_authenticated:
        return redirect(url_for('devices.curl_dashboard'))
    return redirect(url_for('accounts.login'))

webapplikation/iotrace/templates/home.html
{% extends "layout.html" %}
{% set active_page = "home" %}

{% block content %}

<h1>Welcome</h1>
<p>This is a test website, there is using a REST api, that connect to a simple SQL database.</p>
<p>Please press the C.R.U.D links, to see more information.</p>

{% endblock content %}

webapplikation/iotrace/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}">
        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbars/"> 
              
        {% if title %}        
            <title>ioTrace - {{ title }}</title>
        {% else %}
            <title>ioTrace</title>
        {% endif %}    
        {% block head %}{% endblock %} 

        <!-- Bootstrap core CSS -->
        <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        
        <link href="{{url_for('static', filename='css/navbar.css')}}" rel="stylesheet">
                    

    </head>       
    <body style="background-color: #f5f5f5"> 
        <header>

            <img src="{{ url_for('static', filename='images/ioTrace.png') }}" alt="" width="215" height="80">
            <nav class="navbar navbar-expand-sm navbar-light bg-white" aria-label="Third navbar example" style="border:2px solid #89ca84;">
                <div class="container">
                    {% if current_user.is_authenticated %}
                    <a class="navbar-brand" href="/">
                        <img src="{{ url_for('static', filename='images/account/' + current_user.logo_file) }}" alt="123" width="215" height=100% class="center" >
                    </a>
                    {% else %}
                    <a class="navbar-brand" href="/">
                        <img src="{{ url_for('static', filename='images/account/ioTrace.jpg') }}" alt="123" width="215" height=100% class="center" >
                    </a>
                    {% endif %}
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    
                    <!-- Left side -->                
                    <div class="navbar-collapse collapse" id="Navbar">                         
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">                               
                                <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                            </li>
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">                                                      
                                <a class="nav-link" href="{{ url_for('devices.curl_dashboard') }}">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                {% if current_user.devices|length > 0 %}                                                     
                                <a class="nav-link" href="{{ url_for('devices.curl_device', device_id=current_user.devices[0].id) }}">Device Data</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">                                                      
                                <a class="nav-link" href="{{ url_for('devices.add_device') }}">Add Device</a>
                            </li>
                            {% endif %}                      
                        </ul>
                    </div>  
                        <!-- Right side --> 
                    <div class="navbar-collapse collapse" id="Navbar">                    
                        <ul class="navbar-nav ms-auto">
                            {% if current_user.is_authenticated %}
                            {% if current_user.id == 1 or current_user.role == 'admin' %}
                            <li class="nav-item">                              
                                <a class="nav-link" href="/admin">Admin Console</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">                              
                                <a class="nav-link" href="{{ url_for('accounts.account') }}">Account</a>
                            </li>
                            <li class="nav-item">                           
                                <a class="nav-link" href="{{ url_for('accounts.logout') }}">Logout</a> 
                            </li>                                          
                            {% else %}
                            <li class="nav-item">                             
                                <a class="nav-link" href="{{ url_for('accounts.login') }}">Login</a>
                            </li>
                            <li class="nav-item">                              
                                <a class="nav-link" href="{{ url_for('accounts.register') }}">Register</a> 
                            </li>                     
                            {% endif %}
                        </ul>                                                                  
                    </div>
                </div>
            </nav>
        </header>
        
        <main role="main" class="container">
       
                    {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                        {% for category, message in messages %}
                          <div class="alert alert-{{ category }}">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}
                    {% endwith %}
                    
                    {% block content %}{% endblock %}  
        </main>                         
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
</html>