webapplikation/iotrace/devices/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, MacAddress, ValidationError
from iotrace.models import Xtel, Device




class CreateDeviceForm(FlaskForm):
	device_mac = StringField('Device Mac Address', validators=[MacAddress()], render_kw={"placeholder": "00:00:00:00:00:00"})
	devicename = StringField('Device Name', validators=[DataRequired(), Length(min=0, max=20)], render_kw={"placeholder": "Please enter a name"})
	submit = SubmitField('Create Device')

	def validate_device_mac(self, device_mac):
		macaddr = Device.query.filter_by(device_mac=device_mac.data).first()
		if macaddr:
			raise ValidationError('Mac address is used by others.')
		device = Xtel.query.filter_by(device_mac=device_mac.data).first()
		if not device:
			raise ValidationError('The Mac Address is invalid. Please check or contact support.')

class EditDeviceForm(FlaskForm):
	devicename = StringField('Device Name', validators=[DataRequired(), Length(min=0, max=20)])
	mintemp = IntegerField('Device Min Temp', render_kw={"placeholder": "min temp"})
	maxtemp = IntegerField('Device Max Temp', render_kw={"placeholder": "max temp"})
	minhumid = IntegerField('Device Min Humid', render_kw={"placeholder": "min humid"})
	maxhumid = IntegerField('Device Max Humid', render_kw={"placeholder": "max humid"})
	minhpa = IntegerField('Device Min Hpa', render_kw={"placeholder": "min hpa"})
	maxhpa = IntegerField('Device Max Hpa', render_kw={"placeholder": "max hpa"})
	submit = SubmitField('Apply Value')

webapplikation/iotrace/devices/__init__.py
# -*- coding: utf-8 -*-

webapplikation/iotrace/devices/routes.py
import os
from flask import Blueprint, render_template, redirect, request, abort, flash, url_for
from flask_login import login_required, current_user
from iotrace import db
from iotrace.models import Device, DeviceData, TrackingDeviceTrigger, Xtel
from iotrace.devices.forms import CreateDeviceForm, EditDeviceForm
from iotrace.plots.plot import device_temp, device_humid, device_hpa, device_volt, device_lte_rssi, device_pos, all_device_pos, device_alarm1, device_alarm2
from iotrace.curls.curl import curl_all_device_pos, curl_device_temp, curl_device_humid, curl_device_hpa, curl_device_volt, curl_device_lte_rssi, curl_device_pos, curl_device_alarm1, curl_device_alarm2

devices = Blueprint('devices', __name__)

@devices.route('/dashboard')
@login_required
def curl_dashboard():
    devices = Device.query.filter_by(user_id=current_user.id).order_by(Device.devicetype.desc())
    device_data, all_device, GOOGLEMAPS_KEY = curl_all_device_pos(devices)
    logo_file = url_for('static', filename='images/profile_pics/' + current_user.logo_file)
    return render_template('devices/NEWdashboard.html',  title='Dashboard', devices=devices, GOOGLEMAPS_KEY=GOOGLEMAPS_KEY, logo_file=logo_file, all_device=all_device, device_data=device_data)

@devices.route('/dashboard/device/data/<device_id>')
@login_required
def curl_device(device_id):
    device = Device.query.get_or_404(device_id)
    if current_user != device.owner:
        abort(403)
    data = DeviceData.query.filter_by(device_mac=device.device_mac).order_by(DeviceData.timestamp.desc()).all()
    if device.devicetype != 'fire':
        temp = curl_device_temp(data)
        humid = curl_device_humid(data)
        hpa = curl_device_hpa(data)
        volt = curl_device_volt(data)
        lte_rssi = curl_device_lte_rssi(data)
        pos, label, icon, GOOGLEMAPS_KEY= curl_device_pos(device, data)
        return render_template('devices/NEWdevice.html', title=device.devicename, device=device, data=data, device_data=device.data_device, temp=temp, humid=humid, hpa=hpa, volt=volt, lte_rssi=lte_rssi, pos=pos, icon=icon, label=label, GOOGLEMAPS_KEY=GOOGLEMAPS_KEY)

    elif device.devicetype == 'fire':
        alarm_1 = curl_device_alarm1(data)
        alarm_2 = curl_device_alarm2(data)
        volt = curl_device_volt(data)
        lte_rssi = curl_device_lte_rssi(data)       
        return render_template('devices/NEWdevice.html', title=device.devicename, device=device, data=data, device_data=device.data_device, alarm_1=alarm_1, alarm_2=alarm_2, volt=volt, lte_rssi=lte_rssi)

@devices.route('/dashboard/device/new', methods=['GET', 'POST'])
@login_required
def add_device():
    form = CreateDeviceForm()
    if form.validate_on_submit():
        dev = Xtel.query.filter_by(device_mac=form.device_mac.data).first()
        device = Device(device_mac=form.device_mac.data ,devicename=form.devicename.data, devicetype=dev.devicetype, owner=current_user)
        db.session.add(device)
        db.session.commit()
        flash('The device have been added!', 'success')
        return redirect(url_for('devices.curl_dashboard'))
    return render_template('devices/add_device.html', title='Add Device', form=form)

@devices.route('/dashboard/device/edit/<device_id>', methods=['GET', 'POST'])
@login_required
def edit_device(device_id):
    device = Device.query.get_or_404(device_id)
    if device.owner != current_user:
        abort(403)
    value = TrackingDeviceTrigger.query.filter_by(device_id=device.id).first()
    form = EditDeviceForm()
    if value:       
        if form.validate_on_submit():
            device.devicename = form.devicename.data
            value.mintemp = form.mintemp.data
            value.maxtemp = form.maxtemp.data
            value.minhumid = form.minhumid.data
            value.maxhumid = form.maxhumid.data
            value.minhpa = form.minhpa.data
            value.maxhpa = form.maxhpa.data
            db.session.commit()
            flash('Your device has been updated', 'success')
            return redirect(url_for('devices.curl_device', device_id=device.id))
        elif request.method == 'GET':
            form.devicename.data = device.devicename
            form.mintemp.data = value.mintemp
            form.maxtemp.data = value.maxtemp
            form.minhumid.data = value.minhumid
            form.maxhumid.data = value.maxhumid
            form.minhpa.data = value.minhpa
            form.maxhpa.data = value.maxhpa
        return render_template('devices/edit_device.html', title='Update Device', form=form, device=device)
    else:    
        if form.validate_on_submit():
            device.devicename = form.devicename.data
            value = TrackingDeviceTrigger(device_id=device.id ,mintemp=form.mintemp.data, maxtemp=form.maxtemp.data, minhumid=form.minhumid.data, maxhumid=form.maxhumid.data, minhpa=form.minhpa.data, maxhpa=form.maxhpa.data)
            db.session.add(value)
            db.session.commit()
            flash('The values have been added', 'success')
            return redirect(url_for('devices.curl_device', device_id=device.id))
        elif request.method == 'GET':
            form.devicename.data = device.devicename
        return render_template('devices/edit_device.html', title='Update Device', form=form, device=device)



@devices.route('/dashboard/device/delete/<device_id>', methods=['POST'])
@login_required
def delete_device(device_id):
    device = Device.query.get_or_404(device_id)
    if device.owner != current_user:
        abort(403)
    db.session.delete(device)
    db.session.commit()
    flash('Your device has been deleted!', 'success')
    return redirect(url_for('devices.curl_dashboard'))

webapplikation/iotrace/templates/devices/NEWdashboard.html
{% extends "layout.html" %}
{% set active_page = "dashboard" %}

{% block head %}

  <meta http-equiv="refresh" content="60">

{% endblock %}

{% block content %}


<legend class="border-bottom mb-4">Dashboard</legend>
<div class="row justify-content-md-end">
    <div class="col-md-auto">
        <a href="" class="btn btn-outline-success">Update Data</a> 

    </div>   
</div>
<div class="container">
    {% for device in devices %}

        {% if device.devicetype != 'fire' %}
            
                {% if device_data[device.device_mac]|length > 0 %}
                    <div class="row" style="border:1px solid #89ca84;">    
                        <div class="col">
                            <a href="{{ url_for('devices.curl_device', device_id=device.id) }}">{{device.device_mac}}</a>
                        </div>

                        <div class="col">
                            <p>{{device.devicename}}</p>
                        </div>   
                        <div class="col">
                            <img src="{{ url_for('static', filename='images/icon/date_green.png') }}" alt="" width=20px height=20px >
                            {{ device_data[device.device_mac][0].timestamp.strftime('%d-%m-%Y %H:%M:%S')}}
                        </div>
                        <div class="col">
                            <img src="{{ url_for('static', filename='images/icon/temp.png') }}" alt="" width=20px height=20px >
                            {{ device_data[device.device_mac][0].temp }}
                        </div>
                        <div class="col">
                            <img src="{{ url_for('static', filename='images/icon/humid.png') }}" alt="" width=20px height=20px >
                            {{ device_data[device.device_mac][0].humid }}
                        </div>
                        <div class="col">
                            <img src="{{ url_for('static', filename='images/icon/hpa.png') }}" alt="" width=20px height=20px >
                            {{ device_data[device.device_mac][0].hpa }}
                        </div>
                        <div class="col">
                            {% if device_data[device.device_mac][0].volt > 0.500 %}
                            <img src="{{ url_for('static', filename='images/icon/volt_green.png') }}" alt="" width=20px height=20px >
                            {% else %}
                            <img src="{{ url_for('static', filename='images/icon/volt_red.png') }}" alt="" width=20px height=20px >
                            {% endif %}
                            {{ device_data[device.device_mac][0].volt }}
                        </div><div class="col">
                            {% if device_data[device.device_mac][0].lte_rssi > -80 %}
                            <img src="{{ url_for('static', filename='images/icon/lte_rssi_green.png') }}" alt="" width=20px height=20px >
                            {% else %}
                            <img src="{{ url_for('static', filename='images/icon/lte_rssi_red.png') }}" alt="" width=20px height=20px >
                            {% endif %}
                            {{ device_data[device.device_mac][0].lte_rssi }}
                        </div>
                    </div>
                {% endif %}
            
        {% endif %}

        {% if device.devicetype == 'fire' %}
            
                {% if device_data[device.device_mac]|length > 0 %}        
                    <div class="row" style="border:1px solid #89ca84;">    
                        <div class="col">
                            <a href="{{ url_for('devices.curl_device', device_id=device.id) }}">{{device.device_mac}}</a>
                        </div>
                        <div class="col">
                            <p>{{device.devicename}}</p>
                        </div>   
                        <div class="col">
                        <img src="{{ url_for('static', filename='images/icon/date_green.png') }}" alt="" width=20px height=20px >
                        {{ device_data[device.device_mac][0].timestamp.strftime('%d-%m-%Y %H:%M:%S')}}
                    </div>
                    <div class="col">
                        {% if device_data[device.device_mac][0].alarm_1 != true %}
                        <img src="{{ url_for('static', filename='images/icon/hpa_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/hpa_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ device_data[device.device_mac][0].alarm_1 }}
                    </div>
                    <div class="col">
                        {% if device_data[device.device_mac][0].alarm_2 != true %}
                        <img src="{{ url_for('static', filename='images/icon/fire_extinguisher_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/fire_extinguisher_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ device_data[device.device_mac][0].alarm_2 }}
                    </div>
                    <div class="col">
                        {% if device_data[device.device_mac][0].volt > 0.500 %}
                        <img src="{{ url_for('static', filename='images/icon/volt_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/volt_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}                        
                        {{ device_data[device.device_mac][0].volt }}
                    </div><div class="col">
                        {% if device_data[device.device_mac][0].lte_rssi > -80 %}
                        <img src="{{ url_for('static', filename='images/icon/lte_rssi_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/lte_rssi_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ device_data[device.device_mac][0].lte_rssi }}
                    </div>
                    </div>
                {% endif %}
            
        {% endif %}
    {% endfor %}
</div>
<div class="container">
        <div class="row justify-content-md-center">
            
                <div id="map" style="width:50%;height:500px;"></div>
            
        </div>
</div>


<script>
    function initMap() {
        var location = { lat: 55.887635, lng: 9.461349 };
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 6,
            center: location
        });
        {% for device in all_device %}
        var marker = new google.maps.Marker({
            position: { {{device[0]}} },
            map: map,
            icon: "{{ device[2] }}",
            label: "{{ device[1] }}"
        });
        {% endfor %}
    }

</script>

<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLEMAPS_KEY}}&callback=initMap"></script>





{% endblock content %}

webapplikation/iotrace/templates/devices/NEWdevice.html
{% extends "layout.html" %}

{% block head %}

  <meta http-equiv="refresh" content="60">

{% endblock %}

{% block content %}


<div class="container">
    <div class="row justify-content-md-center">
        {%for i in current_user.devices %}
        <div class="col-sm-auto">
            <a href="{{ url_for('devices.curl_device', device_id=i.id) }}" class="btn btn-outline-success">{{loop.index}}</a>
        </div>       
        {%endfor%}
    </div>
</div>


<legend class="border-bottom mb-4">Device Data - {{device.devicename}} </legend>

<div class="row justify-content-md-end ">
    <div class="col-md-auto">
        <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('devices.edit_device', device_id=device.id) }}">Edit Device</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
    </div>
</div>




{% if device.devicetype != 'fire' %}
    <div class="container">
        <div class="row" style="border:1px solid #89ca84;">    
            <div class="col">
                <p>{{device.device_mac}}</p>
            </div>
            
                {% if data[0].device_mac == device.device_mac and data|length > 0 %}  
     
                <div class="col">
                    <img src="{{ url_for('static', filename='images/icon/date.png') }}" alt="" width=20px height=20px >
                    {{ data[0].timestamp}}
                </div>
                <div class="col">
                    <img src="{{ url_for('static', filename='images/icon/temp.png') }}" alt="" width=20px height=20px >
                    {{ data[0].temp }}
                </div>
                <div class="col">
                    <img src="{{ url_for('static', filename='images/icon/humid.png') }}" alt="" width=20px height=20px >
                    {{ data[0].humid }}
                </div>
                <div class="col">
                    <img src="{{ url_for('static', filename='images/icon/hpa.png') }}" alt="" width=20px height=20px >
                    {{ data[0].hpa }}
                </div>
                <div class="col">
                    {% if data[0].volt > 0.500 %}
                    <img src="{{ url_for('static', filename='images/icon/volt_green.png') }}" alt="" width=20px height=20px >
                    {% else %}
                    <img src="{{ url_for('static', filename='images/icon/volt_red.png') }}" alt="" width=20px height=20px >
                    {% endif %}
                    
                    {{ data[0].volt }}
                </div>
                <div class="col">
                    {% if data[0].lte_rssi > -80 %}
                    <img src="{{ url_for('static', filename='images/icon/lte_rssi_green.png') }}" alt="" width=20px height=20px >
                    {% else %}
                    <img src="{{ url_for('static', filename='images/icon/lte_rssi_red.png') }}" alt="" width=20px height=20px >
                    {% endif %}
                    {{ data[0].lte_rssi }}
                </div>
                {% endif %}
            
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <div id="map" style="width:475px;height:400px;"></div>
            </div>
            <div class="col-md-auto">
                <img = src="{{ temp }}" style="width:475px;height:400px;"/>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <img = src="{{ humid }}"style="width:475px;height:400px;"/>
            </div>
            <div class="col-md-auto">
                <img = src="{{ hpa }}"style="width:475px;height:400px;"/>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <img = src="{{ volt }}"style="width:475px;height:400px;"/>
            </div>
            <div class="col-md-auto">
                <img = src="{{ lte_rssi }}"style="width:475px;height:400px;"/>
            </div>
        </div>
    </div>
{% endif %}


{% if device.devicetype == 'fire' %}
    <div class="container">
        <div class="row" style="border:1px solid #89ca84;">    
            <div class="col">
                <p>{{device.device_mac}}</p>
            </div>

            
                {% if data[0].device_mac == device.device_mac and data|length > 0 %}          
                    <div class="col">
                        <img src="{{ url_for('static', filename='images/icon/date_green.png') }}" alt="" width=20px height=20px >
                        {{ data[0].timestamp}}
                    </div>
                    <div class="col">
                        {% if data[0].alarm_1 != true %}
                        <img src="{{ url_for('static', filename='images/icon/hpa_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/hpa_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ data[0].alarm_1 }}
                    </div>
                    <div class="col">
                        {% if data[0].alarm_2 != true %}
                        <img src="{{ url_for('static', filename='images/icon/fire_extinguisher_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/fire_extinguisher_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ data[0].alarm_2 }}
                    </div>
                    <div class="col">
                        {% if data[0].volt > 0.500 %}
                        <img src="{{ url_for('static', filename='images/icon/volt_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/volt_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        
                        {{ data[0].volt }}
                    </div><div class="col">
                        {% if data[0].lte_rssi > -80 %}
                        <img src="{{ url_for('static', filename='images/icon/lte_rssi_green.png') }}" alt="" width=20px height=20px >
                        {% else %}
                        <img src="{{ url_for('static', filename='images/icon/lte_rssi_red.png') }}" alt="" width=20px height=20px >
                        {% endif %}
                        {{ data[0].lte_rssi }}
                    </div>
                {% endif %}
            
        </div>
    </div>
                

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <img = src="{{ alarm_1 }}"style="width:475px;height:400px;"/>
            </div>
            <div class="col-md-auto">
                <img = src="{{ alarm_2 }}"style="width:475px;height:400px;"/>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <img = src="{{ volt }}"style="width:475px;height:400px;"/>
            </div>
            <div class="col-md-auto">
                <img = src="{{ lte_rssi }}"style="width:475px;height:400px;"/>
            </div>
        </div>
    </div>
{% endif %}

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Device?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are your sure that you would like to delete the device?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="{{url_for('devices.delete_device', device_id=device.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
      </div>
    </div>
  </div>
</div>


<script>
    function initMap() {
        var location = { {{ pos }} };
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 10,
            center: location
        });
        var marker = new google.maps.Marker({
            position: location,
            map: map,
            icon: "{{ icon }}",
            label: " {{ label }} "
        });
    }




</script>

<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLEMAPS_KEY}}&callback=initMap"></script>

{% endblock content %}

webapplikation/iotrace/templates/devices/device.html
{% extends "layout.html" %}

{% block content %}

<legend class="border-bottom mb-4">Device Data</legend>
<div class="container">
    <div class="row justify-content-md-center">
        {%for i in current_user.devices %}
        <div class="col-sm-auto">
            <a href="{{ url_for('devices.curl_device', device_id=i.id) }}" class="btn btn-outline-success">{{loop.index}}</a>
        </div>       
        {%endfor%}
    </div>
</div>
<div class="container">
    <div class="row">    
        <div class="col">
            <p>Owner</p>
            <p>{{device.owner.username}}</p>
        </div>
        <div class="col">
            <p>Device Mac</p>
            <p>{{device.device_mac}}</p>
        </div>
        <div class="col">
            <p>Device Name</p>
            <p>{{device.devicename}}</p>
        </div>
        <div class="col">
            <p>Device Type</p>
            <p>{{device.devicetype}}</p>
        </div>
        <div class="col">
            <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('devices.update_device', device_id=device.id) }}">Edit Device</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
        </div>       
    </div>     
</div>


{% if device.devicetype != "fire" and device.data_trackingdevice|length > 0 %}
<div class="container">
    <div class="row">
        <div class="col">
            <p>Time Stamp</p>
            <p>{{ device.data_trackingdevice[0].timestamp }}</p>
        </div>
        <div class="col">
            <p>Temp</p>
            <p>{{ device.data_trackingdevice[0].temp }}</p>
        </div>
        <div class="col">
            <p>Humid</p>
            <p>{{ device.data_trackingdevice[0].humid }}</p>
        </div>
        <div class="col">
            <p>Hpa</p>
            <p>{{ device.data_trackingdevice[0].hpa }}</p>
        </div>
        <div class="col">
            <p>Volt</p>
            <p>{{ device.data_trackingdevice[0].volt }}</p>
        </div>
        <div class="col">
            <p>Lte_rssi</p>
            <p>{{ device.data_trackingdevice[0].lte_rssi }}</p>
        </div>
    </div>
</div>



<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <div id="map" style="width:475px;height:400px;"></div>
        </div>
        <div class="col-md-auto">
            <img = src="{{ temp }}" style="width:475px;height:400px;"/>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <img = src="{{ humid }}"style="width:475px;height:400px;"/>
        </div>
        <div class="col-md-auto">
            <img = src="{{ hpa }}"style="width:475px;height:400px;"/>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <img = src="{{ volt }}"style="width:475px;height:400px;"/>
        </div>
        <div class="col-md-auto">
            <img = src="{{ lte_rssi }}"style="width:475px;height:400px;"/>
        </div>
    </div>
</div>
{% endif %}


{% if device.devicetype == 'fire' and device.data_firedevice|length > 0 %}
<div class="container">
    <div class="row">
        <div class="col">
            <p>Time Stamp</p>
            <p>{{ device.data_firedevice[0].timestamp }}</p>
        </div>
        <div class="col">
            {% if device.data_firedevice[0].alarm_1 != true %}
            <img src="{{ url_for('static', filename='images/icon/alarm_green.png') }}" alt="" width=20px height=20px >
            {% else %}
            <img src="{{ url_for('static', filename='images/icon/alarm_red.png') }}" alt="" width=20px height=20px >
            {% endif %}
            <p>{{ device.data_firedevice[0].alarm_1 }}</p>
        </div>
        <div class="col">
            {% if device.data_firedevice[0].alarm_2 != true %}
            <img src="{{ url_for('static', filename='images/icon/alarm_green.png') }}" alt="" width=20px height=20px >
            {% else %}
            <img src="{{ url_for('static', filename='images/icon/alarm_red.png') }}" alt="" width=20px height=20px >
            {% endif %}
            <p>{{ device.data_firedevice[0].alarm_2 }}</p>
        </div>
        <div class="col">
            <p>Volt</p>
            <p>{{ device.data_firedevice[0].volt }}</p>
        </div>
        <div class="col">
            <p>Lte_rssi</p>
            <p>{{ device.data_firedevice[0].lte_rssi }}</p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <img = src="{{ alarm_1 }}"style="width:475px;height:400px;"/>
        </div>
        <div class="col-md-auto">
            <img = src="{{ alarm_2 }}"style="width:475px;height:400px;"/>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <img = src="{{ volt }}"style="width:475px;height:400px;"/>
        </div>
        <div class="col-md-auto">
            <img = src="{{ lte_rssi }}"style="width:475px;height:400px;"/>
        </div>
    </div>
</div>
{% endif %}

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Device?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are your sure that you would like to delete the device?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="{{url_for('devices.delete_device', device_id=device.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="delete">
        </form>
      </div>
    </div>
  </div>
</div>


<script>
    function initMap() {
        var location = { {{ pos}} };
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 10,
            center: location
        });
        var marker = new google.maps.Marker({
            position: location,
            map: map,
            icon: "{{ icon }}",
            label: " {{ label }} "
        });
    }




</script>

<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLEMAPS_KEY}}&callback=initMap"></script>

{% endblock content %}